title: Yang Bohan's Homepage
page-top-title: Yang Bohan
top-section-bg-text: Artificial Intelligence
home-subtitle: Yang Bohan&ensp;|&ensp;杨博涵
copyright-text: '&copy; Yang Bohan 2025. All Rights Reserved.'
